experiment_name : "default_experiment"
save_path_root : "D:/Projects/singing_models/"
dataset : "commonvoice" # see utils.get_dataset for available datasets & examples
dataset_path : "D:/Projects/common_voice/"
sample_rate : 48000

use_discriminator : False
scratch_train : False

lr : 0.0005
scheduler_warmup : 100 # most scheduler params are hardcoded atm

vae_args : # args for the vae
  in_channels : 1 
  num_quantizers : 10
  codebook_size : 512
  input_format : "n c l"
  vq_cutoff_freq : 0.1
  use_som : True
  som_kernel_type : "hard"
  vq_type : "base"

trainer_args : # these are global args for the trainer
  batch_size : 4
  accumulation_steps : 32
  use_one_discriminator : True
  generator_loss_weight : 0.001
  reconstruction_loss_weight : 100
  codebook_update_step : 1
  steps_per_epoch: 30000
  noise_aug_scale : 0
  discriminator_lr : 0.0015

train_run_args : # these are args for a single run
  epochs : 30
  use_reconstruction_loss : True
  sparsity_weight : 0
  use_commit_loss : True